name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-test:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [10.x, 12.x]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint
    - run: npm test
      env:
        CI: true
        NODE_OPTIONS: "--max_old_space_size=4096"
    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage/coverage.json
        fail_ci_if_error: true

